### ISSUE TITLE
Not possible to use hosted payment pages

### ISSUE THREAD

**Issue by ricovandevin** [gingerpayments/ginger-php#17]
According to the docs it should be possible to make a lightweight integration using the "hosted payment pages".

> To use our hosted payment pages instead of a custom implementation, it is sufficient to send an order request without a payment method and return_url.

With this PHP API client this is not possible since `Client::createOrder()` cannot be used without supplying a payment method.

> Assert\InvalidArgumentException: Value "" is not an element of the valid values: ideal, credit-card, sepa-debit-transfer, sofort, bancontact in Assert\Assertion::createException() (line 212 of /path/to/ginger_php/vendor/beberlei/assert/lib/Assert/Assertion.php).

**Comment by fvdb** [comment]
Fixed in master.

**Comment by ricovandevin** [comment]
So all problem do have a solution if you just wait long enough? ;-) Thanks @fvdb ! Maybe a turn back one day to the Drupal module I was crafting back in January 2017 to finish it.
