### ISSUE TITLE
The SDK depends on a legacy 5.x branch of the «guzzlehttp/guzzle» package

### ISSUE THREAD

**Issue by dmitrii-fediuk** [gingerpayments/ginger-php#19]
https://github.com/gingerpayments/ginger-php/blob/1.2.4/composer.json#L15  
https://packagist.org/packages/guzzlehttp/guzzle 
It leads to Composer conflicts when another package uses a modern version of the `guzzlehttp/guzzle` package ([like your Dutch colleagues from Spryng Payments](https://github.com/spryngpayments/php/blob/v1.1/composer.json#L13)).

**Comment by koemeet** [comment]
This library is pretty unusable because of this.

**Comment by joachimdeboer** [comment]
There's a fork from here: https://github.com/teamlazzo/ginger-php/commits/master with Guzzle 6 support.
It's on Ginger's roadmap to add support soon in our own version, but for speed you could check the above.

**Comment by fvdb** [comment]
Fixed in master. Ginger PHP now comes with its own lightweight HTTP client for compatibility reasons.
